name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'
categories:
  - title: "ðŸ”¥ BREAKING CHANGES"
    labels:
      - "breaking-change"
  - title: "ðŸš€ Features"
    labels:
      - "enhancement"
  - title: "ðŸ› Bug Fixes"
    labels:
      - "bug-fix"
  - title: "ðŸ‘· Chores"
    labels:
      - "chore"
  - title: "âš¡ï¸ Deprecations"
    labels:
      - "deprecation"
  - title: "â¬†ï¸ Dependencies Upgraded"
    labels:
      - "dependency"
exclude-labels:
  - "skip-changelog"
replacers:
  # https://github.com/release-drafter/release-drafter/issues/569#issuecomment-645938155
  - search: '(?:and )?@dependabot(?:\[bot\])?,?'
    replace: ""
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
exclude-contributors:
  - "dependabot"
autolabeler:
  # labels to help with version determination
  - label: "patch"
    title:
      - "/^fix:/i"
      - "/^chore:/i"
      - "/^docs:/i"
      - "/^refactor:/i"
      - "/^test:/i"
      - "/^deprecated:/i"
  - label: "minor"
    title:
      - "/^feat:/i"
      - "/^feature:/i"
  - label: "major"
    title:
      - "/^feat!:/i"
      - "/^feature!:/i"
      - "/^fix!:/i"
      - "/^chore!:/i"
      - "/^docs!:/i"
      - "/^refactor!:/i"
      - "/^test!:/i"
      - "/^deprecated!:/i"
    body:
      - "/BREAKING CHANGE:/"
  # labels to help with changelog grouping
  - label: "dependency"
    title:
      - "/^Bump/" # Dependency update PR by depandabot
  - label: "chore"
    title:
      - "/^docs:/i"
      - "/^chore:/i"
      - "/^refactor:/i"
      - "/^test:/i"
  - label: "enhancements"
    title:
      - "/^feat:/i"
      - "/^feature:/i"
  - label: "bug-fix"
    title:
      - "/^fix:/i"
  - label: "deprecation"
    title:
      - "/^deprecated:/i"
  - label: "breaking-change"
    title:
      - "/^feat!:/i"
      - "/^feature!:/i"
      - "/^fix!:/i"
      - "/^chore!:/i"
      - "/^docs!:/i"
      - "/^refactor!:/i"
      - "/^test!:/i"
      - "/^deprecated!:/i"
    body:
      - "/BREAKING CHANGE:/"
template: |
  ## What's Changed
  $CHANGES