name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'
categories:
  - title: "🔥 BREAKING CHANGES"
    labels:
      - "release-drafter:breaking-change"
  - title: "🚀 Features"
    labels:
      - "release-drafter:enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "release-drafter:bug-fix"
  - title: "👷 Chores"
    labels:
      - "release-drafter:chore"
  - title: "⚡️ Deprecations"
    labels:
      - "release-drafter:deprecation"
  - title: "⬆️ Dependencies Upgraded"
    labels:
      - "release-drafter:dependency"
exclude-labels:
  - "skip-changelog"
replacers:
  # https://github.com/release-drafter/release-drafter/issues/569#issuecomment-645938155
  - search: '(?:and )?@dependabot(?:\[bot\])?,?'
    replace: ""
version-resolver:
  major:
    labels:
      - "release-drafter:major"
      - "release-drafter-go:major"
  minor:
    labels:
      - "release-drafter:minor"
      - "release-drafter-go:minor"
  patch:
    labels:
      - "release-drafter:patch"
      - "release-drafter-go:minor"
  default: patch
exclude-contributors:
  - "dependabot"
autolabeler:
  # labels to help with version determination
  # if you want to play around with the regex here
  # I will suggest doing so on https://regex101.com/
  # it provides good explanation what what the regex is doing
  # If that is not enough, ask chatgpt for help,
  # and then go back to playing with regex on regex101.com
  - label: "release-drafter:patch"
    title:
      # matches in format of "fix: ..."
      # or "fix(scope): ..."
      - '/^(?:fix|chore|docs|doc|refactor|test|deprecated)(?:\((?:[^)]+)\))?:\s.*/i'
  - label: "release-drafter:minor"
    title:
      # matches in format of "feat: ..."
      # or "feat(scope): ..."
      - '/^(?:feat|feature)(?:\((?:[^)]+)\))?:\s.*/i'
  - label: "release-drafter:major"
    title:
      # matches in format of "fix!: ..."
      # or "fix!(scope): ..."
      # or "fix(scope)!: ..."
      - '/^(?:feat|feature|fix|chore|docs|doc|refactor|test|deprecated)(?:!(?:\((?:[^)]+)\))|(?:\((?:[^)]+)\))!|!):\s.*/i'
    body:
      - "/BREAKING CHANGE:/"
  # labels to help with changelog grouping
  - label: "release-drafter:dependency"
    title:
      - '^(?:Bump|(?:chore\(deps\):|chore\(deps-dev\)):)' # Dependency update PR by Dependabot
  - label: "release-drafter:chore"
    title:
      - '/^(?:docs|doc|chore|refactor|test)(?:\((?:[^)]+)\))?:\s.*/i'
  - label: "release-drafter:enhancements"
    title:
      - '/^(?:feat|feature)(?:\((?:[^)]+)\))?:\s.*/i'
  - label: "release-drafter:bug-fix"
    title:
      - '/^fix(?:\((?:[^)]+)\))?:\s.*/i'
  - label: "release-drafter:deprecation"
    title:
      - '/^deprecated(?:\((?:[^)]+)\))?:\s.*/i'
  - label: "release-drafter:breaking-change"
    title:
      - '/^(?:feat|feature|fix|chore|docs|doc|refactor|test|deprecated)(?:!(?:\((?:[^)]+)\))|(?:\((?:[^)]+)\))!|!):\s.*/i'
    body:
      - "/BREAKING CHANGE:/"
template: |
  ## What's Changed
  $CHANGES
